ForwardingService: make the forwarding a safe operation
bitcoinj/bitcoinj pull request #2554
Opened 2022-07-18 23:12 UTC by schildbach

By using a CoinSelector that selects exactly the outputs that have been sent to us,
we make sure that

* we exactly send the value that has been sent to us, minus fee
* if the incoming transaction became invalid (e.g. due to a re-org),
  our outgoing transaction would become invalid, too

Strictly speaking, after this PR we would not need to wait for confirmations any
more.

TODO valueGathered calculation seems a bit hacky
TODO why do we need to calculate our own valueGathered?
TODO maybe extract selector to wallet package, to be used by everyone?

2022-07-18 23:15 UTC, schildbach commented
I've tested this with two concurrent incoming txns that were confirmed in the same block. The value was forwarded with two transaction, each picking the correct corresponding input.

2022-07-19 08:19 UTC, schildbach commented
I've cleared two of the TODOs, rebased against master and tested again (successfully). Marking this as ready for review.

2022-07-19 16:24 UTC, msgilligan requested changes

2022-07-19 16:24 UTC, msgilligan commented on examples/src/main/java/org/bitcoinj/examples/ForwardingService.java
> +    }
This can be simplified to a lambda after we complete PR #2431.

2022-07-19 16:24 UTC, msgilligan commented on examples/src/main/java/org/bitcoinj/examples/ForwardingService.java
>                  // Now send the coins onwards by sending the entire contents of our wallet
This comment is incorrect now that we are adding the CoinSelector.

2022-07-19 16:25 UTC, msgilligan requested changes

2022-07-19 16:28 UTC, msgilligan commented on examples/src/main/java/org/bitcoinj/examples/ForwardingService.java
> +    }
This isn't a suggested change, just a comment. The GitHub review UI is a little bit awkward.

2022-07-19 16:28 UTC, msgilligan commented on examples/src/main/java/org/bitcoinj/examples/ForwardingService.java
> +                sendRequest.coinSelector = new ForwardingCoinSelector(incomingTx);
This one is, in fact, a suggested change.

2022-07-28 21:14 UTC, schildbach commented on examples/src/main/java/org/bitcoinj/examples/ForwardingService.java
> +                sendRequest.coinSelector = new ForwardingCoinSelector(incomingTx);
Thanks! I amended the comment.

2022-07-28 21:23 UTC, merged

2022-07-28 21:24 UTC, schildbach commented
Merged.

2022-07-28 21:52 UTC, msgilligan commented
@schildbach I had a couple more thoughts on this one. I'm glad you merged it, but I think there are some things that can be improved...