Ping, Pong: make (almost) immutable
bitcoinj/bitcoinj pull request #2857
Opened 2023-03-22 18:22 UTC by schildbach

2023-03-22 18:28 UTC, schildbach commented
This is an example of how I would like the Message classes look like.

Note that Ping and Pong so simple they will probably never have data classes (which would go to base). Their "data class" is a long, for the nonce.

Note that the classes are entirely immutable because they extend the still mutable Message class. But at least the classes don't reference the mutable fields (serializer and payload).

2023-03-22 19:04 UTC, msgilligan requested changes
Overall, this looks great! This is a good sign!

I like the `.read(ByteBuffer)` factory method.

I have some minor request and questions, though.

2023-03-22 19:06 UTC, msgilligan commented
> The classes are **not** entirely immutable because they extend the still mutable Message class. But at least the classes don't reference the mutable fields (`serializer` and `payload`).

I fixed what I assume was a typo above by adding the **not**.

2023-03-22 19:12 UTC, schildbach commented on core/src/main/java/org/bitcoinj/core/Ping.java
> +        this.nonce = nonce;
Right, but it's just a private constructor. I'm kind of okay with the permutation explosion for public APIs, but for an internal method?

2023-03-22 19:13 UTC, schildbach commented on core/src/main/java/org/bitcoinj/core/Ping.java
> +    private final Long nonce;
Yes, to discourage nonce-less pings.

2023-03-22 19:16 UTC, schildbach commented on core/src/main/java/org/bitcoinj/core/Peer.java
> +        m.nonce().ifPresent(nonce -> sendMessage(Pong.of(nonce)));
Hmmmm… :confused:

2023-03-22 19:19 UTC, schildbach commented
But actually more than the implementation details I wanted to present an example of how the future could look like.

On that basis, I'd like to start a discussion on how more complex cases like Transactions would look like.

2023-03-22 19:20 UTC, msgilligan commented on core/src/main/java/org/bitcoinj/core/Peer.java
> +        m.nonce().ifPresent(nonce -> sendMessage(Pong.of(nonce)));
Perhaps with line-breaks:
```
m.nonce()
    .map(Pong::of)
    .ifPresent(this::sendMessage);
```

2023-03-22 19:22 UTC, msgilligan commented on core/src/main/java/org/bitcoinj/core/Ping.java
> +        this.nonce = nonce;
I think its worth it to eliminate a boxed `Long` and nullability (not to mention the `@Nullabble` annotation.

2023-03-22 19:57 UTC, msgilligan commented
> We could also remove the nonceless Ping case … nobody is running such old nodes any more.

That is worth considering, but should probably be a separate Issue/PR.

2023-03-22 19:58 UTC, msgilligan commented
> But actually more than the implementation details I wanted to present an example of how the future could look like.

I definitely give this a "concept ack".

> On that basis, I'd like to start a discussion on how more complex cases like Transactions would look like.

What's the next step in that discussion?  I guess I should look at what's left in `Message` that is mutable, for starters...

2023-03-22 20:05 UTC, msgilligan commented on core/src/main/java/org/bitcoinj/core/Ping.java
> +        this.nonce = nonce;
Alternatively, it could be `Ping(long nonce, boolean hasNonce)`

2023-03-23 00:30 UTC, schildbach commented
I pushed an update and I think the two messages are now 100% immutable.

2023-03-23 00:38 UTC, schildbach commented
> > We could also remove the nonceless Ping case … nobody is running such old nodes any more.
> 
> That is worth considering, but should probably be a separate Issue/PR.

It would be extremely easy to implement in current master, before we merge this.

2023-03-23 00:41 UTC, schildbach commented
The current behavior (and the one re-implemented in this PR) is not accurate anyhow. According to BIP31, protocol versions from 60000 upwards have to use (and expect) a nonce.

https://github.com/bitcoin/bips/blob/master/bip-0031.mediawiki

2023-03-23 00:59 UTC, schildbach commented
See https://github.com/bitcoinj/bitcoinj/pull/2861.

2023-03-30 10:18 UTC, schildbach commented
I rebased this draft on all our recent work.

Because we decided to remove support for nonce-less pings a few days ago, I now dropped `Optional` and introduced a new helper: `Ping.pong()`.

2023-03-30 10:20 UTC, schildbach commented on core/src/main/java/org/bitcoinj/core/Peer.java
> +        m.nonce().ifPresent(nonce -> sendMessage(Pong.of(nonce)));
We got rid of the `Optional`, so I resolve this.

2023-03-30 10:20 UTC, schildbach commented on core/src/main/java/org/bitcoinj/core/Ping.java
> +        this.nonce = nonce;
Nonces are now required, so I resolve this.

2023-03-30 10:21 UTC, schildbach commented on core/src/main/java/org/bitcoinj/core/Ping.java
> +        return Optional.ofNullable(nonce);
We got rid of the `Optional`, so I resolve this.

2023-03-30 10:21 UTC, schildbach commented on core/src/main/java/org/bitcoinj/core/Ping.java
> +    public Optional<Long> nonce() {
We got rid of the `Optional`, so I resolve this.

2023-03-30 10:22 UTC, schildbach commented on integration-test/src/test/java/org/bitcoinj/core/FilteredBlockAndPartialMerkleTreeTest.java
> +        inbound(p1, Pong.of(((Ping) ping).nonce().get()));
There is now a `Pong pong = ping.pong()`.

2023-03-30 16:21 UTC, msgilligan approved these changes
Looks great! Why is this still draft?

2023-03-30 17:12 UTC, schildbach commented
I'm still extracting refactorings for it. For now, it's mainly meant as a vision.

2023-03-30 17:14 UTC, schildbach commented
Next step is `parse()` → `static read()`.

2023-04-09 20:20 UTC, msgilligan commented
> Next step is `parse()` → `static read()`.

If PR #3006 is merged and this PR is rebased it can be merged without making a the global  `parse()` → `static read()` change.

2023-04-10 15:58 UTC, schildbach commented
Yes, this could be merged any time, even without rebasing. I'm holding off because I want to make sure we manage to apply the individual refactoring steps on the entire hierarchy. We've had too many migrations stuck at some half-way point in the past, so I'm a bit reluctant.

Currently we're stuck at `Transaction`, and the critical blocker is the `parent` issue. But at least a couple of more sub-messages got divorced from `Message`, which is also great progress imho.

Let me know if the merge status of this PR is blocking anything you're working on.

2023-04-16 08:35 UTC, schildbach commented
Merged.

2023-04-16 08:35 UTC, closed without merging