Ping: require a nonce value
bitcoinj/bitcoinj pull request #2861
Opened 2023-03-23 00:58 UTC by schildbach

Pings without nonce are not protocol compliant since version 60001. Our minimum version is at 70000.

2023-03-23 02:18 UTC, msgilligan requested changes
Looks good. 1 minor change requested `.nonce()` -- **correction:** no change needed!

2023-03-23 02:18 UTC, msgilligan commented on core/src/main/java/org/bitcoinj/core/Ping.java
>      public long getNonce() {
`.getNonce()` can now be just `.nonce()`

2023-03-23 02:21 UTC, msgilligan approved these changes

2023-03-23 02:22 UTC, msgilligan commented on core/src/main/java/org/bitcoinj/core/Ping.java
>      public long getNonce() {
This is out-of-scope (I was a little bit confused by the other pending PR) for this PR. We can fix it when we make Ping immutable.

2023-03-24 12:18 UTC, schildbach commented
Merged.

2023-03-24 12:18 UTC, closed without merging