WalletTool: after `send` action, print the entire transaction
bitcoinj/bitcoinj pull request #3110
Opened 2023-06-13 07:24 UTC by schildbach

Currently, only the transaction hash is printed.

Alternatively, we could add a switch to select txid, tx or nothing. Feels a bit like overkill though.

2023-06-14 20:28 UTC, msgilligan commented
I think we should probably print both the hex transaction and the transaction ID. In most cases, I imagine the first thing the user/developer will do is check a blockchain viewer to see if the transaction has been relayed and they'll need the transaction ID to do that.

2023-06-14 20:32 UTC, msgilligan requested changes
I think we should (always) print both txid and transaction hex -- see my comment: https://github.com/bitcoinj/bitcoinj/pull/3110#issuecomment-1591931438

2023-07-07 14:50 UTC, msgilligan approved these changes
Looks good!

2023-07-07 15:46 UTC, merged

2023-07-07 15:47 UTC, schildbach commented
Merged.