WalletTool: new option for setting the type of filter for syncing
bitcoinj/bitcoinj pull request #3308
Opened 2023-10-07 08:14 UTC by schildbach

Currently, only server-side (bloom) filtering is supported.

Child of #3307

2023-10-10 17:38 UTC, msgilligan requested changes

2023-10-11 08:33 UTC, schildbach commented on wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
> +        SERVER, // bloom filter
For user, the actual filter algorithm is not that important. What counts is if it is a client-side or a server-side filter, with impact on performance and privacy. Nowadays there are BIPs for both and I assume at some point we will implement client-side filtering as well.

2023-10-11 08:33 UTC, schildbach commented on wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
> +        /* CLIENT */
See above.

2023-10-24 11:32 UTC, schildbach commented on wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
> +        SERVER, // bloom filter
Can this be resolved?

2023-10-24 11:32 UTC, schildbach commented on wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
> +        /* CLIENT */
Can this be resolved?

2023-10-24 16:13 UTC, msgilligan approved these changes
Approved. (Though I think `BLOOM` would be more self-explanatory to our intended audience than `SERVER`)

2023-10-24 16:13 UTC, msgilligan commented on wallettool/src/main/java/org/bitcoinj/wallettool/WalletTool.java
> +        /* CLIENT */
I still think `BLOOM` would be more self-explanatory to the majority of our users/developers. But `SERVER` is fine, too.

2023-10-24 21:52 UTC, schildbach commented
Merged.

2023-10-24 21:52 UTC, closed without merging