StoredBlockTest: add tests for serializeCompact(), deserializeCompact(), moreWorkThan()
bitcoinj/bitcoinj pull request #3422
Opened 2024-06-26 21:17 UTC by schildbach

These tests are designed to cover the edge cases around signed/unsigned 12 bytes of chain work.

2024-06-26 21:48 UTC, msgilligan requested changes
You should be able to simplify this code (and make it easier to add test cases) by using `@RunWith(JUnitParamsRunner.class)`.

See [VarIntTest.java](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/test/java/org/bitcoinj/base/VarIntTest.java) for an example.

2024-06-26 22:16 UTC, schildbach commented
A couple of force-pushes later, tests are all green.

And your requested changes applied.

2024-06-27 06:47 UTC, msgilligan approved these changes
Looks good!

2024-06-27 07:02 UTC, schildbach commented
Merged.

2024-06-27 07:02 UTC, closed without merging