Simplify Gradle version comparison in settings.gradle
bitcoinj/bitcoinj pull request #3511
Opened 2024-09-13 20:05 UTC by panic08

I think we should change the version comparison in Gradle to use the “<” operator, since using the comparison operator in GradleVersion under the hood would result in “compareTo” as it is. Also, the code would look more concise that way, I think.

2024-09-14 18:30 UTC, msgilligan approved these changes
I think sometimes we forget that we are using Groovy. This is definitely more readable.

2024-09-15 02:14 UTC, msgilligan requested changes
On second thought, for consistency, this PR should also update line 11 of `settings-debian.gradle` to use a Groovy `==` comparison.

Can you make that change and force-push?

2024-09-15 18:07 UTC, msgilligan approved these changes
Looks good! Thanks!

2024-09-19 17:03 UTC, panic08 commented
**Made a force push as I accidentally committed a commit unrelated to this PR**

2024-09-25 13:08 UTC, schildbach reviewed
I wonder if we should replace those `.compareTo()`s in the various `build.gradle` files as well, for consistency. It's the same Groovy afaik.

2024-09-25 16:20 UTC, panic08 commented
Replacing `.compareTo()` in other `build.gradle` I suppose would be a good idea. Since we are changing .compareTo() for ease of readability, I suppose it would be just as good if we did it in other `build.gradle` as well

2024-09-25 21:39 UTC, msgilligan approved these changes
Even better!

2024-09-25 21:41 UTC, msgilligan commented
Thanks @panic08 !

(This is like when your high school teacher catches you eating M&M's and says "Why don't you share them with the whole class?" 🤣)

2024-10-18 08:12 UTC, closed without merging